In [31]:
text = open('Data/aliceinwonderland.txt')

In [32]:
aiwdata = text.read()

In [33]:
import string

In [34]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [35]:
aiwdata = aiwdata.replace(string.punctuation, ' ')

In [37]:
aiwdata = aiwdata.replace('\n','')

In [39]:
vocab = set(list(aiwdata))

In [41]:
len(vocab)

83

In [42]:
len(aiwdata)

160074

In [43]:
tokenizer = {}

In [79]:
for ct,v in enumerate(vocab):
    tokenizer[v] = ct + 1

In [80]:
tokenizer

{' ': 76,
 '!': 61,
 '"': 64,
 '#': 45,
 '$': 52,
 '%': 30,
 "'": 41,
 '(': 20,
 ')': 74,
 '*': 24,
 ',': 22,
 '-': 59,
 '.': 14,
 '/': 53,
 '0': 27,
 '1': 48,
 '2': 51,
 '3': 58,
 '4': 29,
 '5': 18,
 '6': 39,
 '7': 78,
 '8': 32,
 '9': 60,
 ':': 37,
 ';': 35,
 '?': 7,
 '@': 80,
 'A': 79,
 'B': 40,
 'C': 3,
 'D': 66,
 'E': 63,
 'F': 81,
 'G': 43,
 'H': 54,
 'I': 21,
 'J': 15,
 'K': 34,
 'L': 56,
 'M': 82,
 'N': 71,
 'O': 25,
 'P': 28,
 'Q': 38,
 'R': 50,
 'S': 68,
 'T': 10,
 'U': 19,
 'V': 57,
 'W': 47,
 'X': 83,
 'Y': 11,
 'Z': 36,
 '[': 77,
 ']': 5,
 '_': 62,
 'a': 55,
 'b': 17,
 'c': 1,
 'd': 6,
 'e': 4,
 'f': 46,
 'g': 23,
 'h': 72,
 'i': 13,
 'j': 16,
 'k': 65,
 'l': 42,
 'm': 12,
 'n': 44,
 'o': 26,
 'p': 8,
 'q': 69,
 'r': 9,
 's': 70,
 't': 67,
 'u': 2,
 'v': 31,
 'w': 73,
 'x': 75,
 'y': 33,
 'z': 49}

In [81]:
data_list = []
for c in aiwdata:
    data_list.append(tokenizer[c])

In [82]:
len(data_list[:160000])

160000

In [83]:
data_list = data_list[:160000]

In [84]:
trainX = []
trainY = []

In [85]:
cnt = 0
while True:
    trainX.append(data_list[cnt:cnt+100])
    trainY.append(data_list[cnt+100])
    cnt += 1
    if cnt+101 > 160000:
        break

In [86]:
import numpy as np

In [87]:
X = np.array(trainX)

In [88]:
X.shape

(159900, 100)

In [89]:
Y = np.array(trainY)

In [90]:
Y.shape

(159900,)

In [106]:
from keras.utils import to_categorical

In [107]:
Y = to_categorical(Y)

In [92]:
from keras.layers import LSTM,Dense,Embedding
from keras.models import Sequential

In [109]:
model = Sequential()
model.add(Embedding(input_dim=84, output_dim=28,input_length=100))
model.add(LSTM(64))
model.add(Dense(84, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 100, 28)           2352      
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                23808     
_________________________________________________________________
dense_2 (Dense)              (None, 84)                5460      
Total params: 31,620
Trainable params: 31,620
Non-trainable params: 0
_________________________________________________________________


In [110]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='rmsprop')

In [111]:
model.fit(X,Y, epochs=5, batch_size=50, validation_split=.1)

Train on 143910 samples, validate on 15990 samples
Epoch 1/5
143910/143910 [==============================] - 165s 1ms/step - loss: 2.5133 - acc: 0.3169 - val_loss: 2.8162 - val_acc: 0.2708
Epoch 2/5
143910/143910 [==============================] - 162s 1ms/step - loss: 2.1383 - acc: 0.4133 - val_loss: 2.7408 - val_acc: 0.2986
Epoch 3/5
143910/143910 [==============================] - 162s 1ms/step - loss: 1.9872 - acc: 0.4539 - val_loss: 2.6848 - val_acc: 0.3078
Epoch 4/5
143910/143910 [==============================] - 154s 1ms/step - loss: 1.8886 - acc: 0.4788 - val_loss: 2.6715 - val_acc: 0.3133
Epoch 5/5
143910/143910 [==============================] - 154s 1ms/step - loss: 1.8164 - acc: 0.4966 - val_loss: 2.6066 - val_acc: 0.3304


In [113]:
model.predict_classes(X[:1])

array([76], dtype=int64)

In [114]:
d = X[:1]

In [115]:
d

array([[28,  9, 26, 16,  4,  1, 67, 76, 43,  2, 67,  4, 44, 17,  4,  9,
        23, 41, 70, 76, 79, 42, 13,  1,  4, 41, 70, 76, 79,  6, 31,  4,
        44, 67,  2,  9,  4, 70, 76, 13, 44, 76, 47, 26, 44,  6,  4,  9,
        42, 55, 44,  6, 22, 76, 17, 33, 76, 56,  4, 73, 13, 70, 76,  3,
        55,  9,  9, 26, 42, 42, 10, 72, 13, 70, 76,  4, 40, 26, 26, 65,
        76, 13, 70, 76, 46, 26,  9, 76, 67, 72,  4, 76,  2, 70,  4, 76,
        26, 46, 76, 55]])

In [123]:
d = np.concatenate([d[0][1:],[76]])

In [128]:
model.predict_classes(d.reshape(1,100))

array([42], dtype=int64)

In [129]:
tokenizer

{' ': 76,
 '!': 61,
 '"': 64,
 '#': 45,
 '$': 52,
 '%': 30,
 "'": 41,
 '(': 20,
 ')': 74,
 '*': 24,
 ',': 22,
 '-': 59,
 '.': 14,
 '/': 53,
 '0': 27,
 '1': 48,
 '2': 51,
 '3': 58,
 '4': 29,
 '5': 18,
 '6': 39,
 '7': 78,
 '8': 32,
 '9': 60,
 ':': 37,
 ';': 35,
 '?': 7,
 '@': 80,
 'A': 79,
 'B': 40,
 'C': 3,
 'D': 66,
 'E': 63,
 'F': 81,
 'G': 43,
 'H': 54,
 'I': 21,
 'J': 15,
 'K': 34,
 'L': 56,
 'M': 82,
 'N': 71,
 'O': 25,
 'P': 28,
 'Q': 38,
 'R': 50,
 'S': 68,
 'T': 10,
 'U': 19,
 'V': 57,
 'W': 47,
 'X': 83,
 'Y': 11,
 'Z': 36,
 '[': 77,
 ']': 5,
 '_': 62,
 'a': 55,
 'b': 17,
 'c': 1,
 'd': 6,
 'e': 4,
 'f': 46,
 'g': 23,
 'h': 72,
 'i': 13,
 'j': 16,
 'k': 65,
 'l': 42,
 'm': 12,
 'n': 44,
 'o': 26,
 'p': 8,
 'q': 69,
 'r': 9,
 's': 70,
 't': 67,
 'u': 2,
 'v': 31,
 'w': 73,
 'x': 75,
 'y': 33,
 'z': 49}